-- Run once in Supabase Dashboard → SQL Editor.
-- This schema supports the standalone GitHub Pages dashboard.

create extension if not exists pgcrypto;

create table if not exists public.dashboard_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  row_count integer not null check (row_count >= 0),
  imported_at timestamptz not null default now()
);

create table if not exists public.sales_order_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.dashboard_imports(id) on delete cascade,
  source_row integer not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(import_id, source_row)
);

create index if not exists sales_order_rows_import_id_idx on public.sales_order_rows(import_id);
create index if not exists sales_order_rows_payload_gin_idx on public.sales_order_rows using gin(payload);

alter table public.dashboard_imports enable row level security;
alter table public.sales_order_rows enable row level security;

drop policy if exists "dashboard anon insert imports" on public.dashboard_imports;
create policy "dashboard anon insert imports" on public.dashboard_imports for insert to anon with check (true);
drop policy if exists "dashboard anon read imports" on public.dashboard_imports;
create policy "dashboard anon read imports" on public.dashboard_imports for select to anon using (true);

drop policy if exists "dashboard anon insert rows" on public.sales_order_rows;
create policy "dashboard anon insert rows" on public.sales_order_rows for insert to anon with check (true);
drop policy if exists "dashboard anon read rows" on public.sales_order_rows;
create policy "dashboard anon read rows" on public.sales_order_rows for select to anon using (true);

grant usage on schema public to anon;
grant select, insert on public.dashboard_imports to anon;
grant select, insert on public.sales_order_rows to anon;
grant usage, select on all sequences in schema public to anon;

-- AI analyst rate limiting. Only the Edge Function service role can use it.
create table if not exists public.ai_chat_rate_limits (
  bucket_key text primary key,
  window_started_at timestamptz not null,
  request_count integer not null check (request_count >= 0),
  expires_at timestamptz not null
);

create index if not exists ai_chat_rate_limits_expires_at_idx
  on public.ai_chat_rate_limits(expires_at);

alter table public.ai_chat_rate_limits enable row level security;
revoke all on public.ai_chat_rate_limits from public, anon, authenticated;

create or replace function public.consume_ai_chat_quota(
  p_bucket_key text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_count integer;
  v_expires timestamptz;
begin
  if p_bucket_key is null or length(p_bucket_key) > 160
    or p_limit < 1 or p_limit > 1000
    or p_window_seconds < 1 or p_window_seconds > 604800 then
    raise exception 'invalid quota parameters';
  end if;
  delete from public.ai_chat_rate_limits
  where expires_at < v_now - interval '1 day';
  insert into public.ai_chat_rate_limits (
    bucket_key, window_started_at, request_count, expires_at
  ) values (
    p_bucket_key, v_now, 1,
    v_now + make_interval(secs => p_window_seconds)
  )
  on conflict (bucket_key) do update
  set
    window_started_at = case
      when ai_chat_rate_limits.expires_at <= v_now then v_now
      else ai_chat_rate_limits.window_started_at
    end,
    request_count = case
      when ai_chat_rate_limits.expires_at <= v_now then 1
      else ai_chat_rate_limits.request_count + 1
    end,
    expires_at = case
      when ai_chat_rate_limits.expires_at <= v_now
        then v_now + make_interval(secs => p_window_seconds)
      else ai_chat_rate_limits.expires_at
    end
  returning request_count, expires_at into v_count, v_expires;
  return query select
    v_count <= p_limit,
    greatest(p_limit - v_count, 0),
    v_expires;
end;
$$;

revoke all on function public.consume_ai_chat_quota(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_ai_chat_quota(text, integer, integer)
  to service_role;

-- Shared product classification for every browser using the dashboard.
-- Anonymous writes are temporary until the administrator login is enabled.
create table if not exists public.dashboard_shared_config (
  id text primary key,
  product_mappings jsonb not null default '{}'::jsonb
    check (jsonb_typeof(product_mappings) = 'object'),
  parent_groups jsonb not null default '[]'::jsonb
    check (jsonb_typeof(parent_groups) = 'array'),
  category_definitions jsonb not null default '[]'::jsonb
    check (jsonb_typeof(category_definitions) = 'array'),
  updated_at timestamptz not null default now(),
  constraint dashboard_shared_config_singleton
    check (id = 'product-classification')
);

alter table public.dashboard_shared_config enable row level security;

drop policy if exists "dashboard anon read shared config"
  on public.dashboard_shared_config;
create policy "dashboard anon read shared config"
  on public.dashboard_shared_config
  for select to anon
  using (id = 'product-classification');

drop policy if exists "dashboard anon insert shared config"
  on public.dashboard_shared_config;
create policy "dashboard anon insert shared config"
  on public.dashboard_shared_config
  for insert to anon
  with check (id = 'product-classification');

drop policy if exists "dashboard anon update shared config"
  on public.dashboard_shared_config;
create policy "dashboard anon update shared config"
  on public.dashboard_shared_config
  for update to anon
  using (id = 'product-classification')
  with check (id = 'product-classification');

grant select, insert, update on public.dashboard_shared_config to anon;

-- SECURITY NOTE:
-- These policies are suitable only when the dashboard/data are intentionally shared.
-- For restricted production use, replace anon policies with authenticated-user policies
-- or route uploads through a protected Supabase Edge Function.
