-- Run once in Supabase Dashboard → SQL Editor.
-- This schema supports the standalone GitHub Pages dashboard.

create extension if not exists pgcrypto;

create table if not exists public.dashboard_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  row_count integer not null check (row_count >= 0),
  imported_at timestamptz not null default now()
);

create table if not exists public.sales_order_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.dashboard_imports(id) on delete cascade,
  source_row integer not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(import_id, source_row)
);

create index if not exists sales_order_rows_import_id_idx on public.sales_order_rows(import_id);
create index if not exists sales_order_rows_payload_gin_idx on public.sales_order_rows using gin(payload);

alter table public.dashboard_imports enable row level security;
alter table public.sales_order_rows enable row level security;

drop policy if exists "dashboard anon insert imports" on public.dashboard_imports;
create policy "dashboard anon insert imports" on public.dashboard_imports for insert to anon with check (true);
drop policy if exists "dashboard anon read imports" on public.dashboard_imports;
create policy "dashboard anon read imports" on public.dashboard_imports for select to anon using (true);

drop policy if exists "dashboard anon insert rows" on public.sales_order_rows;
create policy "dashboard anon insert rows" on public.sales_order_rows for insert to anon with check (true);
drop policy if exists "dashboard anon read rows" on public.sales_order_rows;
create policy "dashboard anon read rows" on public.sales_order_rows for select to anon using (true);

grant usage on schema public to anon;
grant select, insert on public.dashboard_imports to anon;
grant select, insert on public.sales_order_rows to anon;
grant usage, select on all sequences in schema public to anon;

-- SECURITY NOTE:
-- These policies are suitable only when the dashboard/data are intentionally shared.
-- For restricted production use, replace anon policies with authenticated-user policies
-- or route uploads through a protected Supabase Edge Function.
