-- SALES & SUPPLY CHAIN — AMERICANSTARUS
-- Foundation migration: dashboard storage, authentication, authorization,
-- master data, Forecast, BOM, inventory, procurement and MRP.

create extension if not exists pgcrypto;

create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------

create or replace function app_private.touch_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Dashboard raw/audit layer
-- ---------------------------------------------------------------------------

create table if not exists public.dashboard_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  row_count integer not null check (row_count >= 0),
  content_hash text,
  data_through_date date,
  import_status text not null default 'complete'
    check (import_status in ('uploading', 'complete', 'failed', 'archived')),
  imported_by uuid references auth.users(id),
  imported_at timestamptz not null default now()
);

create table if not exists public.sales_order_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.dashboard_imports(id) on delete cascade,
  source_row integer not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(import_id, source_row)
);

create index if not exists sales_order_rows_import_id_idx
  on public.sales_order_rows(import_id);
create index if not exists sales_order_rows_payload_gin_idx
  on public.sales_order_rows using gin(payload);

create table if not exists public.dashboard_shared_config (
  id text primary key,
  product_mappings jsonb not null default '{}'::jsonb
    check (jsonb_typeof(product_mappings) = 'object'),
  parent_groups jsonb not null default '[]'::jsonb
    check (jsonb_typeof(parent_groups) = 'array'),
  category_definitions jsonb not null default '[]'::jsonb
    check (jsonb_typeof(category_definitions) = 'array'),
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  constraint dashboard_shared_config_singleton
    check (id = 'product-classification')
);

create table if not exists public.ai_chat_rate_limits (
  bucket_key text primary key,
  window_started_at timestamptz not null,
  request_count integer not null check (request_count >= 0),
  expires_at timestamptz not null
);

create index if not exists ai_chat_rate_limits_expires_at_idx
  on public.ai_chat_rate_limits(expires_at);

-- ---------------------------------------------------------------------------
-- Identity and authorization
-- ---------------------------------------------------------------------------

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role_key text not null default 'viewer'
    check (
      role_key in (
        'admin',
        'sales_admin',
        'supply_admin',
        'planner',
        'sales_user',
        'viewer'
      )
    ),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_access_scopes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.user_profiles(user_id) on delete cascade,
  scope_type text not null
    check (
      scope_type in (
        'salesperson',
        'customer',
        'customer_group',
        'warehouse',
        'industry',
        'business_unit'
      )
    ),
  scope_key text not null,
  created_at timestamptz not null default now(),
  unique(user_id, scope_type, scope_key)
);

create index if not exists user_access_scopes_user_idx
  on public.user_access_scopes(user_id);

create table if not exists public.app_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id),
  action_key text not null,
  entity_type text not null,
  entity_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists app_audit_log_entity_idx
  on public.app_audit_log(entity_type, entity_id);
create index if not exists app_audit_log_created_at_idx
  on public.app_audit_log(created_at desc);

create or replace function app_private.current_user_role()
returns text
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select role_key
  from public.user_profiles
  where user_id = (select auth.uid())
    and is_active = true
  limit 1
$$;

create or replace function app_private.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select
    (select auth.uid()) is not null
    and exists (
      select 1
      from public.user_profiles
      where user_id = (select auth.uid())
        and is_active = true
    )
$$;

create or replace function app_private.has_any_role(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select
    (select auth.uid()) is not null
    and coalesce(app_private.current_user_role() = any(allowed_roles), false)
$$;

revoke all on function app_private.current_user_role() from public;
revoke all on function app_private.is_active_user() from public;
revoke all on function app_private.has_any_role(text[]) from public;
grant usage on schema app_private to authenticated;
grant execute on function app_private.current_user_role() to authenticated;
grant execute on function app_private.is_active_user() to authenticated;
grant execute on function app_private.has_any_role(text[]) to authenticated;

create or replace function app_private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.user_profiles (
    user_id,
    email,
    full_name,
    role_key,
    is_active
  )
  values (
    new.id,
    new.email,
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    'viewer',
    true
  )
  on conflict (user_id) do update
  set email = excluded.email,
      updated_at = now();
  return new;
end;
$$;

revoke all on function app_private.handle_new_auth_user() from public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function app_private.handle_new_auth_user();

-- ---------------------------------------------------------------------------
-- Supply-chain master data
-- ---------------------------------------------------------------------------

create table if not exists public.business_units (
  id uuid primary key default gen_random_uuid(),
  unit_code text not null unique,
  unit_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.business_units (unit_code, unit_name)
values ('FOAM', 'Foam'), ('MATTRESS', 'Mattress')
on conflict (unit_code) do nothing;

create table if not exists public.warehouses (
  id uuid primary key default gen_random_uuid(),
  warehouse_code text not null unique,
  warehouse_name text not null,
  state_code text,
  location_group text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_master (
  id uuid primary key default gen_random_uuid(),
  product_code text not null unique,
  product_name text not null,
  product_family text,
  parent_group text,
  category_name text,
  business_unit_id uuid references public.business_units(id),
  lifecycle_status text
    check (
      lifecycle_status is null
      or lifecycle_status in ('new', 'growth', 'decline', 'stable', 'death')
    ),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_master_business_unit_idx
  on public.product_master(business_unit_id);
create index if not exists product_master_category_idx
  on public.product_master(parent_group, category_name);

create table if not exists public.item_master (
  id uuid primary key default gen_random_uuid(),
  item_code text not null unique,
  item_name text not null,
  item_type text not null
    check (
      item_type in (
        'finished_good',
        'semi_finished',
        'raw_material',
        'component',
        'packaging',
        'service'
      )
    ),
  base_uom text not null,
  item_group text,
  business_unit_id uuid references public.business_units(id),
  is_buy boolean not null default true,
  is_make boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists item_master_business_unit_idx
  on public.item_master(business_unit_id);
create index if not exists item_master_type_idx
  on public.item_master(item_type);

create table if not exists public.product_item_map (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.product_master(id) on delete cascade,
  item_id uuid not null references public.item_master(id) on delete cascade,
  source_product_model text,
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  unique(product_id, item_id)
);

create index if not exists product_item_map_product_idx
  on public.product_item_map(product_id);
create index if not exists product_item_map_item_idx
  on public.product_item_map(item_id);

create table if not exists public.uom_conversions (
  id uuid primary key default gen_random_uuid(),
  item_id uuid references public.item_master(id) on delete cascade,
  from_uom text not null,
  to_uom text not null,
  factor numeric(18,6) not null check (factor > 0),
  created_at timestamptz not null default now(),
  unique nulls not distinct (item_id, from_uom, to_uom)
);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  supplier_code text not null unique,
  supplier_name text not null,
  email text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supplier_item_policy (
  id uuid primary key default gen_random_uuid(),
  supplier_id uuid not null references public.suppliers(id) on delete cascade,
  item_id uuid not null references public.item_master(id) on delete cascade,
  lead_time_days integer not null default 0 check (lead_time_days >= 0),
  moq_qty numeric(18,4) not null default 0 check (moq_qty >= 0),
  lot_size_qty numeric(18,4) not null default 0 check (lot_size_qty >= 0),
  safety_stock_qty numeric(18,4) not null default 0 check (safety_stock_qty >= 0),
  service_level numeric(7,6)
    check (service_level is null or service_level between 0 and 1),
  unit_cost numeric(18,4),
  currency_code text not null default 'USD',
  is_preferred boolean not null default false,
  active_from date not null default current_date,
  active_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(supplier_id, item_id),
  check (active_to is null or active_to >= active_from)
);

-- ---------------------------------------------------------------------------
-- Inventory and inbound supply
-- ---------------------------------------------------------------------------

create table if not exists public.inventory_balance (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.item_master(id) on delete cascade,
  warehouse_id uuid not null references public.warehouses(id) on delete cascade,
  on_hand_qty numeric(18,4) not null default 0,
  allocated_qty numeric(18,4) not null default 0,
  quality_hold_qty numeric(18,4) not null default 0,
  inbound_qty numeric(18,4) not null default 0,
  updated_at timestamptz not null default now(),
  unique(item_id, warehouse_id)
);

create table if not exists public.inventory_snapshot (
  id uuid primary key default gen_random_uuid(),
  snapshot_date date not null,
  item_id uuid not null references public.item_master(id) on delete cascade,
  warehouse_id uuid not null references public.warehouses(id) on delete cascade,
  on_hand_qty numeric(18,4) not null default 0,
  allocated_qty numeric(18,4) not null default 0,
  quality_hold_qty numeric(18,4) not null default 0,
  inbound_qty numeric(18,4) not null default 0,
  created_at timestamptz not null default now(),
  unique(snapshot_date, item_id, warehouse_id)
);

create index if not exists inventory_snapshot_date_idx
  on public.inventory_snapshot(snapshot_date desc);

create table if not exists public.purchase_order_header (
  id uuid primary key default gen_random_uuid(),
  po_number text not null unique,
  supplier_id uuid not null references public.suppliers(id),
  warehouse_id uuid references public.warehouses(id),
  status text not null default 'draft'
    check (
      status in (
        'draft',
        'approved',
        'ordered',
        'partial',
        'received',
        'closed',
        'cancelled'
      )
    ),
  order_date date not null default current_date,
  expected_date date,
  created_by uuid references auth.users(id),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_order_line (
  id uuid primary key default gen_random_uuid(),
  po_id uuid not null references public.purchase_order_header(id) on delete cascade,
  item_id uuid not null references public.item_master(id),
  ordered_qty numeric(18,4) not null check (ordered_qty > 0),
  received_qty numeric(18,4) not null default 0 check (received_qty >= 0),
  unit_cost numeric(18,4),
  due_date date,
  line_no integer not null,
  created_at timestamptz not null default now(),
  unique(po_id, line_no)
);

-- ---------------------------------------------------------------------------
-- BOM
-- ---------------------------------------------------------------------------

create table if not exists public.bom_header (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.product_master(id) on delete cascade,
  bom_code text not null,
  revision text not null default 'R1',
  output_qty numeric(18,6) not null default 1 check (output_qty > 0),
  output_uom text not null,
  effective_from date not null default current_date,
  effective_to date,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'obsolete')),
  created_by uuid references auth.users(id),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(bom_code, revision),
  check (effective_to is null or effective_to >= effective_from)
);

create index if not exists bom_header_product_idx
  on public.bom_header(product_id);

create table if not exists public.bom_line (
  id uuid primary key default gen_random_uuid(),
  bom_id uuid not null references public.bom_header(id) on delete cascade,
  component_item_id uuid not null references public.item_master(id),
  qty_per numeric(18,6) not null check (qty_per > 0),
  component_uom text not null,
  scrap_factor numeric(10,6) not null default 0
    check (scrap_factor between 0 and 1),
  yield_factor numeric(10,6) not null default 1
    check (yield_factor > 0 and yield_factor <= 1),
  line_no integer not null,
  created_at timestamptz not null default now(),
  unique(bom_id, line_no),
  unique(bom_id, component_item_id)
);

create index if not exists bom_line_bom_idx
  on public.bom_line(bom_id);

-- ---------------------------------------------------------------------------
-- Demand Forecast
-- ---------------------------------------------------------------------------

create table if not exists public.forecast_version (
  id uuid primary key default gen_random_uuid(),
  version_name text not null unique,
  scenario text not null default 'base'
    check (scenario in ('base', 'upside', 'downside')),
  status text not null default 'draft'
    check (status in ('draft', 'submitted', 'approved', 'locked', 'archived')),
  planning_grain text not null default 'product'
    check (planning_grain in ('product', 'sku', 'item')),
  start_month date not null,
  end_month date not null,
  algorithm_key text,
  algorithm_parameters jsonb not null default '{}'::jsonb,
  source_import_id uuid references public.dashboard_imports(id),
  created_by uuid references auth.users(id),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (date_trunc('month', start_month)::date = start_month),
  check (date_trunc('month', end_month)::date = end_month),
  check (end_month >= start_month)
);

create table if not exists public.forecast_line (
  id uuid primary key default gen_random_uuid(),
  version_id uuid not null references public.forecast_version(id) on delete cascade,
  product_id uuid references public.product_master(id),
  item_id uuid references public.item_master(id),
  warehouse_id uuid references public.warehouses(id),
  demand_month date not null,
  statistical_qty numeric(18,4) not null default 0,
  override_qty numeric(18,4),
  final_qty numeric(18,4) generated always as (
    coalesce(override_qty, statistical_qty)
  ) stored,
  lower_bound_qty numeric(18,4),
  upper_bound_qty numeric(18,4),
  accuracy_mape numeric(10,6),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((product_id is not null)::integer + (item_id is not null)::integer = 1),
  check (date_trunc('month', demand_month)::date = demand_month),
  unique nulls not distinct (
    version_id,
    product_id,
    item_id,
    warehouse_id,
    demand_month
  )
);

create index if not exists forecast_line_version_month_idx
  on public.forecast_line(version_id, demand_month);

-- ---------------------------------------------------------------------------
-- MRP
-- ---------------------------------------------------------------------------

create table if not exists public.mrp_run (
  id uuid primary key default gen_random_uuid(),
  run_name text not null,
  forecast_version_id uuid references public.forecast_version(id),
  planning_start date not null,
  planning_end date not null,
  status text not null default 'draft'
    check (status in ('draft', 'running', 'completed', 'approved', 'archived', 'failed')),
  parameters jsonb not null default '{}'::jsonb,
  error_message text,
  created_by uuid references auth.users(id),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  check (planning_end >= planning_start)
);

create table if not exists public.mrp_recommendation (
  id uuid primary key default gen_random_uuid(),
  mrp_run_id uuid not null references public.mrp_run(id) on delete cascade,
  item_id uuid not null references public.item_master(id),
  warehouse_id uuid references public.warehouses(id),
  recommendation_type text not null
    check (
      recommendation_type in (
        'buy',
        'build',
        'expedite',
        'defer',
        'cancel',
        'reallocate'
      )
    ),
  requirement_date date not null,
  required_qty numeric(18,4) not null default 0,
  available_qty numeric(18,4) not null default 0,
  scheduled_receipt_qty numeric(18,4) not null default 0,
  supply_gap_qty numeric(18,4) not null default 0,
  suggested_order_qty numeric(18,4) not null default 0,
  suggested_release_date date,
  lead_time_days integer check (lead_time_days is null or lead_time_days >= 0),
  supplier_id uuid references public.suppliers(id),
  priority text not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'critical')),
  status text not null default 'open'
    check (status in ('open', 'accepted', 'converted', 'dismissed')),
  note text,
  created_at timestamptz not null default now()
);

create index if not exists mrp_recommendation_run_idx
  on public.mrp_recommendation(mrp_run_id);
create index if not exists mrp_recommendation_item_date_idx
  on public.mrp_recommendation(item_id, requirement_date);

-- ---------------------------------------------------------------------------
-- Updated-at triggers
-- ---------------------------------------------------------------------------

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'user_profiles',
    'business_units',
    'warehouses',
    'product_master',
    'item_master',
    'suppliers',
    'supplier_item_policy',
    'purchase_order_header',
    'bom_header',
    'forecast_version',
    'forecast_line'
  ]
  loop
    execute format(
      'drop trigger if exists %I on public.%I',
      target_table || '_touch_updated_at',
      target_table
    );
    execute format(
      'create trigger %I before update on public.%I for each row execute function app_private.touch_updated_at()',
      target_table || '_touch_updated_at',
      target_table
    );
  end loop;
end
$$;

-- ---------------------------------------------------------------------------
-- RLS and Data API grants
-- ---------------------------------------------------------------------------

do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'dashboard_imports',
    'sales_order_rows',
    'dashboard_shared_config',
    'ai_chat_rate_limits',
    'user_profiles',
    'user_access_scopes',
    'app_audit_log',
    'business_units',
    'warehouses',
    'product_master',
    'item_master',
    'product_item_map',
    'uom_conversions',
    'suppliers',
    'supplier_item_policy',
    'inventory_balance',
    'inventory_snapshot',
    'purchase_order_header',
    'purchase_order_line',
    'bom_header',
    'bom_line',
    'forecast_version',
    'forecast_line',
    'mrp_run',
    'mrp_recommendation'
  ]
  loop
    execute format('alter table public.%I enable row level security', target_table);
  end loop;
end
$$;

-- The current dashboard remains anonymously readable during the account rollout.
-- All writes on the new project require an authenticated, authorized user.
drop policy if exists dashboard_anon_read_imports on public.dashboard_imports;
create policy dashboard_anon_read_imports
on public.dashboard_imports for select to anon
using (import_status = 'complete');

drop policy if exists dashboard_active_users_read_imports on public.dashboard_imports;
create policy dashboard_active_users_read_imports
on public.dashboard_imports for select to authenticated
using ((select app_private.is_active_user()));

drop policy if exists dashboard_authorized_create_imports on public.dashboard_imports;
create policy dashboard_authorized_create_imports
on public.dashboard_imports for insert to authenticated
with check (
  (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
  and imported_by = (select auth.uid())
);

drop policy if exists dashboard_authorized_update_imports on public.dashboard_imports;
create policy dashboard_authorized_update_imports
on public.dashboard_imports for update to authenticated
using (
  (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
)
with check (
  (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
);

drop policy if exists dashboard_anon_read_rows on public.sales_order_rows;
create policy dashboard_anon_read_rows
on public.sales_order_rows for select to anon
using (
  exists (
    select 1
    from public.dashboard_imports i
    where i.id = import_id
      and i.import_status = 'complete'
  )
);

drop policy if exists dashboard_active_users_read_rows on public.sales_order_rows;
create policy dashboard_active_users_read_rows
on public.sales_order_rows for select to authenticated
using ((select app_private.is_active_user()));

drop policy if exists dashboard_authorized_insert_rows on public.sales_order_rows;
create policy dashboard_authorized_insert_rows
on public.sales_order_rows for insert to authenticated
with check (
  (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
  and exists (
    select 1
    from public.dashboard_imports i
    where i.id = import_id
      and i.imported_by = (select auth.uid())
  )
);

drop policy if exists dashboard_anon_read_shared_config
  on public.dashboard_shared_config;
create policy dashboard_anon_read_shared_config
on public.dashboard_shared_config for select to anon
using (id = 'product-classification');

drop policy if exists dashboard_active_users_read_shared_config
  on public.dashboard_shared_config;
create policy dashboard_active_users_read_shared_config
on public.dashboard_shared_config for select to authenticated
using ((select app_private.is_active_user()));

drop policy if exists dashboard_authorized_insert_shared_config
  on public.dashboard_shared_config;
create policy dashboard_authorized_insert_shared_config
on public.dashboard_shared_config for insert to authenticated
with check (
  id = 'product-classification'
  and updated_by = (select auth.uid())
  and (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
);

drop policy if exists dashboard_authorized_update_shared_config
  on public.dashboard_shared_config;
create policy dashboard_authorized_update_shared_config
on public.dashboard_shared_config for update to authenticated
using (
  id = 'product-classification'
  and (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
)
with check (
  id = 'product-classification'
  and updated_by = (select auth.uid())
  and (select app_private.has_any_role(
    array['admin', 'sales_admin', 'supply_admin', 'planner']::text[]
  ))
);

drop policy if exists users_read_own_profile on public.user_profiles;
create policy users_read_own_profile
on public.user_profiles for select to authenticated
using (
  user_id = (select auth.uid())
  or (select app_private.current_user_role()) = 'admin'
);

drop policy if exists admins_update_profiles on public.user_profiles;
create policy admins_update_profiles
on public.user_profiles for update to authenticated
using ((select app_private.current_user_role()) = 'admin')
with check ((select app_private.current_user_role()) = 'admin');

drop policy if exists users_read_own_scopes on public.user_access_scopes;
create policy users_read_own_scopes
on public.user_access_scopes for select to authenticated
using (
  user_id = (select auth.uid())
  or (select app_private.current_user_role()) = 'admin'
);

drop policy if exists admins_manage_scopes on public.user_access_scopes;
create policy admins_manage_scopes
on public.user_access_scopes for all to authenticated
using ((select app_private.current_user_role()) = 'admin')
with check ((select app_private.current_user_role()) = 'admin');

drop policy if exists admins_read_audit_log on public.app_audit_log;
create policy admins_read_audit_log
on public.app_audit_log for select to authenticated
using ((select app_private.current_user_role()) = 'admin');

-- Active accounts can read reference and planning data.
do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'business_units',
    'warehouses',
    'product_master',
    'item_master',
    'product_item_map',
    'uom_conversions',
    'suppliers',
    'supplier_item_policy',
    'inventory_balance',
    'inventory_snapshot',
    'purchase_order_header',
    'purchase_order_line',
    'bom_header',
    'bom_line',
    'forecast_version',
    'forecast_line',
    'mrp_run',
    'mrp_recommendation'
  ]
  loop
    execute format('drop policy if exists active_users_read on public.%I', target_table);
    execute format(
      'create policy active_users_read on public.%I for select to authenticated using ((select app_private.is_active_user()))',
      target_table
    );
  end loop;
end
$$;

-- Supply administrators manage master, inventory, BOM and purchasing data.
do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'business_units',
    'warehouses',
    'product_master',
    'item_master',
    'product_item_map',
    'uom_conversions',
    'suppliers',
    'supplier_item_policy',
    'inventory_balance',
    'inventory_snapshot',
    'purchase_order_header',
    'purchase_order_line',
    'bom_header',
    'bom_line'
  ]
  loop
    execute format('drop policy if exists supply_roles_manage on public.%I', target_table);
    execute format(
      'create policy supply_roles_manage on public.%I for all to authenticated using ((select app_private.has_any_role(array[''admin'', ''supply_admin'', ''planner'']::text[]))) with check ((select app_private.has_any_role(array[''admin'', ''supply_admin'', ''planner'']::text[])))',
      target_table
    );
  end loop;
end
$$;

-- Planning roles manage forecasts and MRP runs.
do $$
declare
  target_table text;
begin
  foreach target_table in array array[
    'forecast_version',
    'forecast_line',
    'mrp_run',
    'mrp_recommendation'
  ]
  loop
    execute format('drop policy if exists planning_roles_manage on public.%I', target_table);
    execute format(
      'create policy planning_roles_manage on public.%I for all to authenticated using ((select app_private.has_any_role(array[''admin'', ''supply_admin'', ''planner'']::text[]))) with check ((select app_private.has_any_role(array[''admin'', ''supply_admin'', ''planner'']::text[])))',
      target_table
    );
  end loop;
end
$$;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select on public.dashboard_imports to anon;
grant select on public.sales_order_rows to anon;
grant select on public.dashboard_shared_config to anon;

grant select, insert, update on public.dashboard_imports to authenticated;
grant select, insert on public.sales_order_rows to authenticated;
grant select, insert, update on public.dashboard_shared_config to authenticated;
grant select, update on public.user_profiles to authenticated;
grant select, insert, update, delete on public.user_access_scopes to authenticated;
grant select on public.app_audit_log to authenticated;
grant select, insert, update, delete on
  public.business_units,
  public.warehouses,
  public.product_master,
  public.item_master,
  public.product_item_map,
  public.uom_conversions,
  public.suppliers,
  public.supplier_item_policy,
  public.inventory_balance,
  public.inventory_snapshot,
  public.purchase_order_header,
  public.purchase_order_line,
  public.bom_header,
  public.bom_line,
  public.forecast_version,
  public.forecast_line,
  public.mrp_run,
  public.mrp_recommendation
to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke all on public.ai_chat_rate_limits from public, anon, authenticated;

-- Used only by the AI Edge Function through the service-role key.
create or replace function public.consume_ai_chat_quota(
  p_bucket_key text,
  p_limit integer,
  p_window_seconds integer
)
returns table(allowed boolean, remaining integer, reset_at timestamptz)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_count integer;
  v_expires timestamptz;
begin
  if p_bucket_key is null
    or length(p_bucket_key) > 160
    or p_limit < 1
    or p_limit > 1000
    or p_window_seconds < 1
    or p_window_seconds > 604800 then
    raise exception 'invalid quota parameters';
  end if;

  delete from public.ai_chat_rate_limits
  where expires_at < v_now - interval '1 day';

  insert into public.ai_chat_rate_limits (
    bucket_key,
    window_started_at,
    request_count,
    expires_at
  )
  values (
    p_bucket_key,
    v_now,
    1,
    v_now + make_interval(secs => p_window_seconds)
  )
  on conflict (bucket_key) do update
  set
    window_started_at = case
      when ai_chat_rate_limits.expires_at <= v_now then v_now
      else ai_chat_rate_limits.window_started_at
    end,
    request_count = case
      when ai_chat_rate_limits.expires_at <= v_now then 1
      else ai_chat_rate_limits.request_count + 1
    end,
    expires_at = case
      when ai_chat_rate_limits.expires_at <= v_now
        then v_now + make_interval(secs => p_window_seconds)
      else ai_chat_rate_limits.expires_at
    end
  returning request_count, expires_at into v_count, v_expires;

  return query
  select
    v_count <= p_limit,
    greatest(p_limit - v_count, 0),
    v_expires;
end;
$$;

revoke all on function public.consume_ai_chat_quota(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.consume_ai_chat_quota(text, integer, integer)
  to service_role;
