-- Versioned Fishbowl Purchase Order imports used by Ongoing Supply and
-- Supplier Pricing. Each item payload contains its inherited parent PO fields.

create table if not exists public.purchase_order_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  row_count integer not null check (row_count >= 0),
  po_count integer not null default 0 check (po_count >= 0),
  content_hash text,
  data_through_date date,
  import_status text not null default 'uploading'
    check (import_status in ('uploading', 'complete', 'failed', 'archived')),
  imported_by uuid references auth.users(id),
  imported_at timestamptz not null default now()
);

create table if not exists public.purchase_order_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null
    references public.purchase_order_imports(id) on delete cascade,
  source_row integer not null,
  po_number text not null,
  source_status_id integer not null,
  scheduled_date date,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(import_id, source_row)
);

create index if not exists purchase_order_rows_import_id_idx
  on public.purchase_order_rows(import_id);
create index if not exists purchase_order_rows_po_number_idx
  on public.purchase_order_rows(po_number);
create index if not exists purchase_order_rows_status_schedule_idx
  on public.purchase_order_rows(source_status_id, scheduled_date);
create index if not exists purchase_order_rows_payload_gin_idx
  on public.purchase_order_rows using gin(payload);

alter table public.purchase_order_imports enable row level security;
alter table public.purchase_order_rows enable row level security;

drop policy if exists purchase_order_imports_read on public.purchase_order_imports;
create policy purchase_order_imports_read
on public.purchase_order_imports
for select
to authenticated
using ((select app_private.is_active_user()));

drop policy if exists purchase_order_imports_manage on public.purchase_order_imports;
create policy purchase_order_imports_manage
on public.purchase_order_imports
for all
to authenticated
using (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
)
with check (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
);

drop policy if exists purchase_order_rows_read on public.purchase_order_rows;
create policy purchase_order_rows_read
on public.purchase_order_rows
for select
to authenticated
using ((select app_private.is_active_user()));

drop policy if exists purchase_order_rows_manage on public.purchase_order_rows;
create policy purchase_order_rows_manage
on public.purchase_order_rows
for all
to authenticated
using (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
)
with check (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
);

revoke all on public.purchase_order_imports from anon;
revoke all on public.purchase_order_rows from anon;
grant select, insert, update, delete on public.purchase_order_imports to authenticated;
grant select, insert, update, delete on public.purchase_order_rows to authenticated;
grant usage, select on sequence public.purchase_order_rows_id_seq to authenticated;
