-- Versioned Fishbowl BOM imports. Only BOM ACTIVE=TRUE rows are retained by
-- the application. Repeated components are intentionally stored as separate
-- lines because a mattress may use the same material in multiple layers.

create table if not exists public.bom_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  source_row_count integer not null check (source_row_count >= 0),
  active_row_count integer not null check (active_row_count >= 0),
  stored_row_count integer not null check (stored_row_count >= 0),
  bom_count integer not null check (bom_count >= 0),
  output_count integer not null check (output_count >= 0),
  component_line_count integer not null check (component_line_count >= 0),
  excluded_bom_count integer not null default 0 check (excluded_bom_count >= 0),
  excluded_boms jsonb not null default '[]'::jsonb,
  content_hash text,
  import_status text not null default 'uploading'
    check (import_status in ('uploading', 'complete', 'failed', 'archived')),
  imported_by uuid references auth.users(id),
  imported_at timestamptz not null default now()
);

alter table public.bom_imports
  add column if not exists excluded_boms jsonb not null default '[]'::jsonb;

create table if not exists public.bom_import_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null references public.bom_imports(id) on delete cascade,
  source_row integer not null,
  bom_number text not null,
  bom_description text,
  revision text not null,
  item_type text not null check (item_type in ('Finished Good', 'Raw Good')),
  item_description text,
  part_number text not null,
  quantity numeric(24,10) not null check (quantity > 0),
  uom text not null,
  configuration_sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(import_id, source_row)
);

create table if not exists public.bom_mrp_selections (
  output_part_number text primary key,
  bom_number text not null,
  revision text not null,
  selected_by uuid references auth.users(id),
  selected_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bom_import_rows_import_id_idx
  on public.bom_import_rows(import_id);
create index if not exists bom_import_rows_output_idx
  on public.bom_import_rows(import_id, item_type, part_number);
create index if not exists bom_import_rows_bom_idx
  on public.bom_import_rows(import_id, bom_number, revision);

alter table public.bom_imports enable row level security;
alter table public.bom_import_rows enable row level security;
alter table public.bom_mrp_selections enable row level security;

drop policy if exists bom_imports_read on public.bom_imports;
create policy bom_imports_read
on public.bom_imports for select to authenticated
using ((select app_private.is_active_user()));

drop policy if exists bom_imports_manage on public.bom_imports;
create policy bom_imports_manage
on public.bom_imports for all to authenticated
using ((select app_private.has_any_role(array['admin', 'supply_admin', 'planner'])))
with check ((select app_private.has_any_role(array['admin', 'supply_admin', 'planner'])));

drop policy if exists bom_import_rows_read on public.bom_import_rows;
create policy bom_import_rows_read
on public.bom_import_rows for select to authenticated
using ((select app_private.is_active_user()));

drop policy if exists bom_import_rows_manage on public.bom_import_rows;
create policy bom_import_rows_manage
on public.bom_import_rows for all to authenticated
using ((select app_private.has_any_role(array['admin', 'supply_admin', 'planner'])))
with check ((select app_private.has_any_role(array['admin', 'supply_admin', 'planner'])));

drop policy if exists bom_mrp_selections_read on public.bom_mrp_selections;
create policy bom_mrp_selections_read
on public.bom_mrp_selections for select to authenticated
using ((select app_private.is_active_user()));

drop policy if exists bom_mrp_selections_manage on public.bom_mrp_selections;
create policy bom_mrp_selections_manage
on public.bom_mrp_selections for all to authenticated
using ((select app_private.has_any_role(array['admin', 'supply_admin', 'planner'])))
with check ((select app_private.has_any_role(array['admin', 'supply_admin', 'planner'])));

revoke all on public.bom_imports from anon;
revoke all on public.bom_import_rows from anon;
revoke all on public.bom_mrp_selections from anon;
grant select, insert, update, delete on public.bom_imports to authenticated;
grant select, insert, update, delete on public.bom_import_rows to authenticated;
grant select, insert, update, delete on public.bom_mrp_selections to authenticated;
grant usage, select on sequence public.bom_import_rows_id_seq to authenticated;
