-- Versioned Fishbowl Part Master imports.
-- Part Number is immutable and is the shared bridge between sales, purchasing,
-- inventory, BOM, forecast and MRP datasets.

create table if not exists public.part_master_imports (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  row_count integer not null check (row_count >= 0),
  active_row_count integer not null default 0 check (active_row_count >= 0),
  content_hash text,
  import_status text not null default 'uploading'
    check (import_status in ('uploading', 'complete', 'failed', 'archived')),
  imported_by uuid references auth.users(id),
  imported_at timestamptz not null default now()
);

create table if not exists public.part_master_rows (
  id bigint generated by default as identity primary key,
  import_id uuid not null
    references public.part_master_imports(id) on delete cascade,
  source_row integer not null,
  part_number text not null,
  normalized_part_number text not null,
  is_active boolean not null default false,
  part_group text,
  industry text,
  consolidated_product_name text,
  parent_group text,
  declared_category text,
  lifecycle_status text
    check (
      lifecycle_status is null
      or lifecycle_status in ('new', 'growth', 'decline', 'stable', 'death')
    ),
  lead_time_days integer check (lead_time_days is null or lead_time_days >= 0),
  payload jsonb not null,
  created_at timestamptz not null default now(),
  unique(import_id, source_row),
  unique(import_id, part_number)
);

create index if not exists part_master_rows_import_id_idx
  on public.part_master_rows(import_id);
create index if not exists part_master_rows_part_number_idx
  on public.part_master_rows(part_number);
create index if not exists part_master_rows_normalized_part_number_idx
  on public.part_master_rows(normalized_part_number);
create index if not exists part_master_rows_active_group_idx
  on public.part_master_rows(is_active, part_group);
create index if not exists part_master_rows_classification_idx
  on public.part_master_rows(industry, parent_group, declared_category);
create index if not exists part_master_rows_payload_gin_idx
  on public.part_master_rows using gin(payload);

alter table public.part_master_imports enable row level security;
alter table public.part_master_rows enable row level security;

drop policy if exists part_master_imports_read on public.part_master_imports;
create policy part_master_imports_read
on public.part_master_imports
for select
to authenticated
using ((select app_private.is_active_user()));

drop policy if exists part_master_imports_manage on public.part_master_imports;
create policy part_master_imports_manage
on public.part_master_imports
for all
to authenticated
using (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
)
with check (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
);

drop policy if exists part_master_rows_read on public.part_master_rows;
create policy part_master_rows_read
on public.part_master_rows
for select
to authenticated
using ((select app_private.is_active_user()));

drop policy if exists part_master_rows_manage on public.part_master_rows;
create policy part_master_rows_manage
on public.part_master_rows
for all
to authenticated
using (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
)
with check (
  (select app_private.has_any_role(array['admin', 'supply_admin', 'planner']))
);

revoke all on public.part_master_imports from anon;
revoke all on public.part_master_rows from anon;
grant select, insert, update, delete on public.part_master_imports to authenticated;
grant select, insert, update, delete on public.part_master_rows to authenticated;
grant usage, select on sequence public.part_master_rows_id_seq to authenticated;

-- Retire the old hand-maintained product classification payload. The app now
-- derives the hierarchy and product mapping only from the current Part import.
delete from public.dashboard_shared_config
where id = 'product-classification';
